name: test_tecnico
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc_concurrency: ^0.3.0
  connectivity_plus: ^7.0.0
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  http: ^1.5.0
  stream_transform: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/BRL.png
    - assets/images/COP.png
    - assets/images/PEN.png
    - assets/images/VES.png
    - assets/images/TATUM-TRON-USDT.png
